pip install requests
pip install pycryptodome
pip install pystyle
pip install colorama
pip install auto_py_to_exe
pip install pyinstaller
pip install wmi
pip install pyOpenSSL
pip install OpenSSL
pip install get-mac
pip install psutil
pip install ctypes
pip install Crypto.Cipher
pip install fade
pip install discord
pip install browser_cookie3
pip install discord_webhook
